### ISSUE TITLE
Analog Pins 4 and 5 Read()

### ISSUE THREAD

**Issue by friedhardware-zz** [galileo-chofrock/pyGalileo#5]
When trying to read from Analog pin 4, I receive an error with this traceback:

```
 File "/home/root/WaterPumpFirmware/Things.py", line 61, in read_pumpTemp
    read1= analogRead(pumpTempSensorPin);
  File "/home/root/WaterPumpFirmware/pyGalileo/__init__.py", line 192, in analogRead
    value = _pins.analogPins[int(num)].GetValue();
  File "/home/root/WaterPumpFirmware/pyGalileo/GalileoPins.py", line 803, in GetValue
    self._Initialize();
  File "/home/root/WaterPumpFirmware/pyGalileo/GalileoPins.py", line 775, in _Initialize
    self._Setup2Mux();
  File "/home/root/WaterPumpFirmware/pyGalileo/GalileoPins.py", line 725, in _Setup2Mux
    self.self._WriteFile("/sys/class/gpio/export",self._mux2Pin);
AttributeError: AnalogPin instance has no attribute 'self'
```

This is how I am calling it:

```
  read= analogRead(A4);
```

**Comment by galileo-chofrock** [comment]
I believe this is now fixed. The problem was a typo in line 725. 
Was:
     self.self._WriteFile("/sys/class/gpio/export",self._mux2Pin);
Now: 
     self._WriteFile("/sys/class/gpio/export",self._mux2Pin);

**Comment by 4aviraj** [comment]
Traceback (most recent call last):
  File "Datalogger.py", line 75, in <module>
    loop();
  File "Datalogger.py", line 46, in loop
    sensorValue4 = analogRead(sensorPin4);
  File "/media/mmcblk0p1/pyGalileo/**init**.py", line 192, in analogRead
    value = _pins.analogPins[int(num)].GetValue();
  File "/media/mmcblk0p1/pyGalileo/GalileoPins.py", line 803, in GetValue
    self._Initialize();
  File "/media/mmcblk0p1/pyGalileo/GalileoPins.py", line 775, in _Initialize
    self._Setup2Mux();
  File "/media/mmcblk0p1/pyGalileo/GalileoPins.py", line 744, in _Setup2Mux
    if(direction == OUTPUT):
NameError: global name 'direction' is not defined

I am getting this error while accessing analog read function for pin 4 and 5.
Please help me.
